// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-my-trips.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.96.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-my-trips.ts
var list_my_trips_default = defineTool({
  name: "list_my_trips",
  title: "List my trips",
  description: "List the signed-in user's saved trip itineraries (destination, status, created date).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum number of trips to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("saved_itineraries").select("id, destination, status, created_at, updated_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { trips: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-trip.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_trip_default = defineTool2({
  name: "get_trip",
  title: "Get trip details",
  description: "Get the full itinerary data and preferences for one of the signed-in user's saved trips.",
  inputSchema: {
    trip_id: z2.string().uuid().describe("The id of the saved trip, from list_my_trips.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ trip_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("saved_itineraries").select("id, destination, status, preferences, itinerary_data, created_at, updated_at").eq("id", trip_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) throw new ToolError(`No trip found with id ${trip_id}`);
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { trip: data }
    };
  }
});

// src/lib/mcp/tools/search-destinations.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var search_destinations_default = defineTool3({
  name: "search_destinations",
  title: "Search destinations",
  description: "Search published destination guides available in the app by destination or title.",
  inputSchema: {
    query: z3.string().trim().min(1).describe("Destination or keyword to search for, e.g. 'Goa'."),
    limit: z3.number().int().min(1).max(25).default(10).describe("Maximum number of results.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("itineraries").select("id, title, destination, cover_image_url, updated_at").eq("is_published", true).or(`destination.ilike.%${query}%,title.ilike.%${query}%`).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { destinations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-trip-expenses.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_trip_expenses_default = defineTool4({
  name: "list_trip_expenses",
  title: "List trip expenses",
  description: "List the signed-in user's recorded travel expenses, optionally filtered to a single trip.",
  inputSchema: {
    trip_id: z4.string().uuid().nullable().default(null).describe("Optional trip id to filter expenses by."),
    limit: z4.number().int().min(1).max(100).default(50).describe("Maximum number of expenses to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ trip_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("trip_expenses").select("id, trip_id, amount, currency, category, description, expense_date").order("expense_date", { ascending: false }).limit(limit ?? 50);
    if (trip_id) query = query.eq("trip_id", trip_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const total = (data ?? []).reduce((sum, e) => sum + Number(e.amount ?? 0), 0);
    return {
      content: [{ type: "text", text: JSON.stringify({ total, expenses: data ?? [] }) }],
      structuredContent: { total, expenses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-trip-expense.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var add_trip_expense_default = defineTool5({
  name: "add_trip_expense",
  title: "Add trip expense",
  description: "Record a new travel expense for the signed-in user, optionally linked to a saved trip.",
  inputSchema: {
    amount: z5.number().positive().describe("Expense amount."),
    category: z5.string().trim().min(1).default("general").describe("Expense category, e.g. food, transport, stay."),
    description: z5.string().trim().nullable().default(null).describe("Optional note about the expense."),
    currency: z5.string().trim().default("INR").describe("Currency code, defaults to INR."),
    expense_date: z5.string().nullable().default(null).describe("Date in YYYY-MM-DD; defaults to today."),
    trip_id: z5.string().uuid().nullable().default(null).describe("Optional saved trip id to attach the expense to.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ amount, category, description, currency, expense_date, trip_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("trip_expenses").insert({
      user_id: ctx.getUserId(),
      amount,
      category: category || "general",
      description: description ?? null,
      currency: currency || "INR",
      ...expense_date ? { expense_date } : {},
      trip_id: trip_id ?? null
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { expense: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "twfvlbianbqkrmyjyxnp";
var mcp_default = defineMcp({
  name: "kro-travel-planner",
  title: "Kro Travel Planner",
  version: "0.1.0",
  instructions: "Tools for Kro Travel Planner. Use `list_my_trips` and `get_trip` to read the signed-in user's saved itineraries, `search_destinations` to browse published destination guides, and `list_trip_expenses` / `add_trip_expense` to review or record travel spending.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_trips_default, get_trip_default, search_destinations_default, list_trip_expenses_default, add_trip_expense_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
